import * from "../src/install_command.ab"
import * from "github.com/lens0021/testchamber/asserts.ab"

pub fun test_pkg_parse(): Null? {
    let parsed = pkg_parse("github.com/foo/bar/main.ab")
    assert_eq(parsed[0], "github.com/foo/bar")?
    assert_eq(parsed[1], "main.ab")?

    parsed = pkg_parse("github.com/foo/bar/src/main.ab")
    assert_eq(parsed[0], "github.com/foo/bar")?
    assert_eq(parsed[1], "src/main.ab")?
}

